# Generated by Django 5.2.8 on 2025-11-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('visitor_contact', models.CharField(max_length=50)),
                ('visitor_purpose', models.CharField(blank=True, max_length=50)),
                ('visit_date', models.DateField()),
                ('visit_created_at', models.DateField()),
            ],
        ),
    ]
