# Generated by Django 5.2.8 on 2025-11-27 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='visit_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
