# Generated by Django 5.2.8 on 2025-11-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_alter_visitors_visit_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='visit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
